import classNames from 'classnames';
import Link from 'next/link';
import { HTMLAttributes } from 'react';

export default function Disclaimer({
  className,
  ...props
}: HTMLAttributes<HTMLDivElement>) {
  return (
    <div className={classNames('grid grid-cols-1 gap-2', className)} {...props}>
      <p>
        Disclaimer: FourScore is an independent platform and is not affiliated
        with any government agency, political party, or election commission, nor
        does it represent any government entity. All government-related
        information is sourced from publicly available data and official
        government websites. The candidate alignments and &quot;Four
        Scores&quot; generated by our platform are based on independent research
        and publicly available information, unless a candidate has directly
        signed up with FourScore and completed our detailed policy survey. In
        such cases, the alignment reflects the candidate&apos;s self-reported
        policy positions. FourScore strives to ensure accuracy and transparency
        in all its data but does not endorse any political candidates or
        parties.
      </p>
      <div className='grid grid-cols-[min-content_1fr] gap-2'>
        <p>Sources:</p>
        <ul className='list-disc list-outside ml-3 text-left'>
          <li>
            Voter registration information:
            <br />
            <Link
              className='underline'
              href='https://www.usa.gov/register-to-vote'
              target='_blank'
              rel='noopener noreferrer'
            >
              USA.gov
            </Link>
          </li>
          <li>
            Election dates and details:
            <br />
            <Link
              className='underline'
              href='https://www.fec.gov/'
              target='_blank'
              rel='noopener noreferrer'
            >
              Federal Election Commission
            </Link>
          </li>
          <li>
            Policy positions:
            <br />
            Publicly available candidate websites and official statements
          </li>
        </ul>
      </div>
    </div>
  );
}
