import { HTMLAttributes } from 'react';

export default function Disclaimer(props: HTMLAttributes<HTMLDivElement>) {
  return (
    <div {...props}>
      Disclaimer: FourScore is an independent platform and is not affiliated with any government agency, political party, or election commission. Our goal is to provide voters with information and tools to make informed decisions based on policy alignment. The candidate alignments and "Four Scores" generated by our platform are based on independent research and publicly available information, unless a candidate has directly signed up with FourScore and completed our detailed policy survey. In such cases, the alignment reflects the candidate's self-reported policy positions. FourScore strives to ensure accuracy and transparency in all its data but does not endorse any political candidates or parties.
    </div>
  );
}
